import type { VideoSource } from '@/lib/types';

// 高级模式视频源 (Premium / 18+) — 22 条源
export const PREMIUM_SOURCES: VideoSource[] = [
    {
        id: 'hsck',
        name: '黄色仓库',
        baseUrl: 'https://hsckzy.vip',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 1,
    },
    {
        id: 'leba',
        name: '乐播资源',
        baseUrl: 'https://lbapi9.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 2,
    },
    {
        id: 'ck',
        name: 'CK',
        baseUrl: 'https://www.ckzy1.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 3,
    },
    {
        id: 'jkun',
        name: 'jkun',
        baseUrl: 'https://jkunzyapi.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 4,
    },
    {
        id: '155',
        name: '155',
        baseUrl: 'https://155api.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 5,
    },
    {
        id: 'lsb',
        name: 'lsb',
        baseUrl: 'https://apilsbzy1.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 6,
    },
    {
        id: 'yutu',
        name: '玉兔',
        baseUrl: 'https://yutuzy10.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 7,
    },
    {
        id: 'msnii',
        name: '美少女资源站',
        baseUrl: 'https://www.msnii.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 8,
    },
    {
        id: 'xrbsp',
        name: '淫水机资源站',
        baseUrl: 'https://www.xrbsp.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 9,
    },
    {
        id: 'gdlsp',
        name: '香奶儿资源站',
        baseUrl: 'https://www.gdlsp.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 10,
    },
    {
        id: 'kxgav',
        name: '白嫖资源站',
        baseUrl: 'https://www.kxgav.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 11,
    },
    {
        id: 'pgxdy',
        name: '黄AV资源站',
        baseUrl: 'https://www.pgxdy.com',
        searchPath: '/api/json.php',
        detailPath: '/api/json.php',
        group: 'premium',
        enabled: true,
        priority: 12,
    },
    {
        id: 'baiwan',
        name: '百万资源',
        baseUrl: 'https://api.bwzyz.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 13,
    },
    {
        id: 'madou',
        name: '91麻豆',
        baseUrl: 'https://91md.me',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 14,
    },
    {
        id: 'aosika',
        name: '奥斯卡资源',
        baseUrl: 'https://aosikazy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 15,
    },
    {
        id: 'naixiang',
        name: '奶香香',
        baseUrl: 'https://Naixxzy.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 16,
    },
    {
        id: 'senlin',
        name: '森林资源',
        baseUrl: 'https://slapibf.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 17,
    },
    {
        id: 'fanhao',
        name: '番号资源',
        baseUrl: 'http://fhapi9.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 18,
    },
    {
        id: 'jingpin',
        name: '精品资源',
        baseUrl: 'https://www.jingpinx.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 19,
    },
    {
        id: 'shayu',
        name: '鲨鱼资源',
        baseUrl: 'https://shayuapi.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 20,
    },
    {
        id: 'xiaoji',
        name: '小鸡资源',
        baseUrl: 'https://api.xiaojizy.live',
        searchPath: '/provide/vod',
        detailPath: '/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 21,
    },
    {
        id: 'xibao',
        name: '细胞采集',
        baseUrl: 'https://www.xxibaozyw.com',
        searchPath: '/api.php/provide/vod',
        detailPath: '/api.php/provide/vod',
        group: 'premium',
        enabled: true,
        priority: 22,
    },
];
